### ISSUE TITLE
Add Smartlook to the service

### ISSUE THREAD

**Issue by stevenjmesser** [digital-land/lpa-data-validator-frontend#109]
# Problem statement

Users at local planning authorities are time-poor, and engaging them in moderated or unmoderated testing sessions is hard. This means we have less opportunity to test the service with our users and we lose important evidence that can help us better design or improve the service.

# Solution

We’ll implement [Smartlook](https://www.smartlook.com/) on the end-to-end service for Data Providers which allows us to observe user sessions and log how they use the service, highlighting problems, pain points and successful journeys.

# Tech Approach

[needs scoping and planning with @GeorgeGoodall]

You can find the developer docs at https://help.smartlook.com/docs/getting-started

Code for implementing Smartlook is as follows:

```
<script type='text/javascript'>
  window.smartlook||(function(d) {
    var o=smartlook=function(){ o.api.push(arguments)},h=d.getElementsByTagName('head')[0];
    var c=d.createElement('script');o.api=new Array();c.async=true;c.type='text/javascript';
    c.charset='utf-8';c.src='https://web-sdk.smartlook.com/recorder.js';h.appendChild(c);
    })(document);
    smartlook('init', '6383ab27d6f6a02f043a518bea629cd232dc0131', { region: 'eu' });
</script>
```

# Acceptance criteria

- Should be recording sessions on production but not staging/development, as this will use up our quota of sessions
- It’s obviously fine to implement it on staging/development initially to test it’s working, but once tested it should ideally only run on production
- No need to identify specific visitors
- No need to record specific form inputs
- We’ll give users the option to [opt out](https://help.smartlook.com/docs/opt-out-of-smartlook) in the privacy notice

# Tasks

- [ ] https://github.com/digital-land/lpa-data-validator-frontend/pull/119
- [x] Write content for privacy and cookies notices
- [ ] https://github.com/digital-land/lpa-data-validator-frontend/pull/107
- [ ] Test implementation
- [ ] (Other tasks as necessary)
