### ISSUE TITLE
Make the Nunjucks template and have it render correctly

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/lpa-data-validator-frontend#131]
This card involves making the template for the LPA finder page

## ToDo:
- [x] Write initial empty/incomplete test files to lead development of this page (TE: 2 hours)
- [x] update controller to pass through hardcoded variables to the template, until we are ready to fetch and obtain real data from datasette/the api (TE: 2 hours)
- [x] Write the nunjucks template (TE: 2 hours)
- [x] Complete the initial tests to align them with the final template (TE: 6 hours)
