### ISSUE TITLE
LPA Dashboard: Performance Database & Related Tables

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/lpa-data-validator-frontend#149]
### **Overview**

For the Providers' LPA Dashboard, we need to create a new Performance database in datasette and related tables to house the data for the various metrics displayed by the dashboard. This ticket is broken up into 3 sub-tasks below:

Create the database in datasette

Create the Organisation summary table based on all provisions

Create an organisation provision table based on all provisions

### **Tech Approach**

Creating the DB in https://datasette.planning.data.gov.uk/

Defining the structure of each table.

org_summary table:
no of datasets provided
datasets_errors
datasets_warnings (warnings)

provision_summary table:
dataset
organisation
no_of_entites
no_of_healthy_endpoints
no_of_unhealthy_endpoints
no_of_errors
no_of_warning

### **Acceptance Criteria/Tests**

- [ ] The Performance Database exists ready for use by the Providers team to be available at https://datasette.planning.data.gov.uk/
- [ ] The relevant tables have been created and are populated using provision data

### **Resourcing**
To be completed alongside #3324 which will create the database and tables this API will use.

### **Tasks**

- [x] Create Performance database via datasette
- [x] Create Organisation Summary table
- [x] Push the new database in S3 bucket
- [x] Get the perf DB on datasette (via efs-sync)

**Comment by Darren-CheckPlanningData** [comment]
Samriti Sadhu [3 Jul 2024, 14:33]
(https://trello.com/c/dRDz4oRm/3327-lpa-dashboard-performance-database-related-tables#comment-668553118f103b07f5726e4d)

Note: Refer [digital-land: provision: 4,605 rows] (https://datasette.planning.data.gov.uk/digital-land/provision) table
