### ISSUE TITLE
Epic: LPA Finder

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/lpa-data-validator-frontend#152]
### **What**

Ability for a user to select the LPA / organisation that they're a part of

### **Problem statement**

LPAs and Interested organisations need to be able to get to a dashboard page for the org or LPA they are interested in, without asking for a url. Access to the dashboards should be transparent and not hidden.

### **User story**

> As a data provider 
> I want to find and view my organisation’s page
> so that I can see what datasets we need to provide and our progress towards providing the required datasets

### **Tech Approach**
Proposal:
Alex Torrance
July 16th @9:47 PM on Slack channel #providers-team-planning-data

For the organisations page we should use the list-filter module from GOV.UK as that will have been accessibility tested and it follows the same pattern.
Example: https://www.gov.uk/world
Page source: https://github.com/alphagov/collections/blob/main/app/views/world/index.html.erb
Javascript source: https://github.com/alphagov/collections/blob/main/app/assets/javascripts/modules/list-filter.js

### **Acceptance criteria**

- [ ] User can find their organisation within the list presented on the page
- [ ] User can filter the list using search criteria
- [ ] Search criteria offers a list of possible matches for the text supplies as the user enters the text into a search field
- [ ] Clicking on a listed organisation will open a dashboard page for that organisation
- [ ] The presented list of organisations is listed in alphabetical order so that a user can navigate the list easily, should they have difficulty or are unable to use the search feature.

### **Known Artefacts**

Definitive list of orgs that should be used to populate the LPA finder org list:

https://datasette.planning.data.gov.uk/digital-land/organisation

Not just LPAs who provide data —

https://tpximpact.slack.com/archives/C04T2E0CZ0D/p1716467326728739

Current Design
![Image](https://github.com/user-attachments/assets/9a363c46-6c28-41ff-a291-5cbc57877e94)
https://design-sprint-prototype-8e5ca5d98540.herokuapp.com/overview/v2/organisations

### **Linked Tasks**

- [ ] https://github.com/digital-land/lpa-data-validator-frontend/issues/130
- [ ] https://github.com/digital-land/lpa-data-validator-frontend/issues/131
- [ ] https://github.com/digital-land/lpa-data-validator-frontend/issues/132
- [ ] https://github.com/digital-land/lpa-data-validator-frontend/issues/133
- [ ] https://github.com/digital-land/lpa-data-validator-frontend/issues/134
- [ ] https://github.com/digital-land/lpa-data-validator-frontend/issues/135
- [ ] https://github.com/digital-land/lpa-data-validator-frontend/issues/136
