### ISSUE TITLE
Epic: Step-by-Step Flow for Providing Data

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/lpa-data-validator-frontend#154]
### **What**

List of steps for the data provider to follow to check, publish and provide their data

### **Problem statement**

LPAs have fed back that is it difficult to know where to start when providing data and can find the guidance confusing.

### **User stories**

> As a data provider
> I want to understand what we have to do to provide a dataset to the platform
> so that I can prepare the data
> 
> 
> 
> As a data provider
> I want to understand the specific tasks we need to complete to prepare, check, publish and provide our data
> so that we can complete the process easily
> 
> 
> 
> As a data provider
> When I get stuck with the processI want to receive prompt support
> so that I can quickly resolve the issue and get back on with my job
> 
> 
> 
> As a data provider
> When I return to the task list at a point in time after I've already completed some tasks
> I want the task list to have saved my progress
> so that I am able to pick up where I left off

### **Acceptance criteria**

- [ ] User is able to click through to see the steps involved in each task, taking a one-action-at-a-time approach (one-per-page)
- [ ] User can easily find directions (on the same page) to further guidance that will help them complete each step
- [ ] User can easily find directions (on the same page) to support portal and link(s) to the status of data they have already supplied and link to the check tool to check data not already supplied

### **Known Artefacts**

Current Design

![Image](https://github.com/user-attachments/assets/d130b6a2-b67d-4a5f-8814-8af6470c1c0c)
