### ISSUE TITLE
Fix broken & miss directed links

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/lpa-data-validator-frontend#286]
### Acceptance criteria (outcomes expected that make this work complete)

- [ ]  Users can navigate successfully to the page in the chain they have followed using the breadcrumb navigation trail URL links at the top of each page
- [ ] All URL links take a user to the correct page

### Tasks (list of todo's for this work)

- [x]  Dashboard: ‘Not provided’ card not linking to the ‘get-started’ page for the dataset
- [x]  URL pointing at staging instead of the live page(see, e.g.,[ this page](https://check.planning.data.gov.uk/organisations/local-authority:LBH/tree-preservation-zone))
- [x]  All pages: Breadcrumb missing, links at the top of the page that let you navigate to previous pages in the chain
- [x]  Top-most level breadcrumb missing capitalization
- [ ]  Issue page: Users should be able to tab through the records - missing pagination
- [ ] Issue page: Should filter record to show the relevant entry (e.g. in[ this example](https://check.planning.data.gov.uk/organisations/local-authority:LBH/listed-building-outline/missing%20value), record 949 has 2 fields that are missing values - if the user clicks on the hyperlink, they end up on[ the right page](https://check.planning.data.gov.uk/organisations/local-authority:LBH/listed-building-outline/missing%20value/949)).
- [ ] Org Finder: LPA finder: if you type the first letter for an entity, it doesn't filter to the start of the list for that letter.. e.g I type in ‘C’ or ‘c’ it doesn't filter to show only what is under C in the list. Not sure if this is by design to allow for partial name search. Maybe one for user testing to see what users would expect/like?

### Supporting artefacts (what previous work / current work / discussions / etc, that will help complete this work)
